### ISSUE TITLE
Errors when attempting to run container on Raspberry Pi and macOS

### ISSUE THREAD

**Issue by brettdavies** [indiefan/home_assistant_nanit#3]
When executing the shell script or attempting to start the container, I get one of two errors (see below). The macOS Error is thrown when attempting to run the container. On macOS, I can execute the script without error. The Raspberry Pi Error is thrown when attempting to run the container and when the script is executed.

For me, the higher priority is stability on Raspberry Pi. I was only attempting to run the container on macOS to help troubleshoot.

**Articles with areas to explore**
https://davidcasr.medium.com/docker-standard-init-linux-go-211-exec-user-process-caused-no-such-file-or-directory-en-c0cb42edb295
https://beebom.com/how-fix-exec-user-process-caused-exec-format-error-linux/

Regarding line endings, I cannot find any shell files except for init-nanit.sh. That file already has ([LF endings](https://github.dev/indiefan/home_assistant_nanit/blob/main/scripts/init-nanit.sh)), so, to me, that is not likely to be the solution to this issue.

**macOS Ventura 13.4 Error**
```
exec /app/bin/nanit: no such file or directory
```

**Raspberry Pi Error**
```
standard_init_linux.go:219: exec user process caused: no such file or directory
```

**Shell script**
```
docker run -it -v ~/data:/data --entrypoint=/app/scripts/init-nanit.sh indiefan/nanit:latest
```

**Docker**
```
docker run   --name=nanit   --restart unless-stopped   -v ~/data:/data   -e NANIT_RTMP_ADDR=10.0.0.5:1935   -e NANIT_LOG_LEVEL=trace   -p 1935:1935   indiefan/nanit:latest
```

**Docker Compose**
```
  nanit:
    container_name: nanit
    image: indiefan/nanit:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - 'NANIT_RTMP_ADDR=10.0.0.5:1935'
      - NANIT_LOG_LEVEL=trace
    volumes:
      - './data:/data'
    ports:
      - 1935:1935
```
